apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: freqtrade:freqai_rl_ds
      kaniko:
        cache: {}
  cluster:
    pullSecretName: e2esecret
manifests:
  rawYaml:
  - k8s-*